const categories = [
    "Groceries & Food Supplies",
    "Personal Care & Hygiene",
    "Office Supplies",
    "Electronics & Gadgets",
    "Fashion & Apparel",
    "Baby & Kids",
    "Automotive",
    "Health & Medical",
    "Sports & Outdoors",
    "Pet Supplies",
    "Cosmetics & Beauty",
    "Books & Media",
    "Home Appliances",
    "Art & Craft",
    "Industrial Supply",
    "Travel & Luggage",
    "Jewelry & Watches",
    "Party & Event Supplies",
    "Musical Instruments",
    "Tools & Hardware",
    "Home Entertainment",
    "Furniture & Decor",
    "Photography & Videography",
    "Toys & Hobbies",
    "Kitchen & Dining",
    "Religious & Cultural",
    "Wines & Spirits",
    "Seasonal & Holiday Items",
    "Automotive Care",
    "Gardening & Outdoor",
    "Fitness & Wellness",
    "Gifts & Souvenirs",
    "Safety & Security",
    "Baby Gear",
    "Stationery & School Supplies",
    "Construction Materials",
    "Eco-Friendly Products",
    "Wigs & Hair"
  ];

  export default categories